Repository tailscale/tailscale, pull requests merged in 2025-01, with the labels that each got.

#14452 wgengine/router: refactor udm-pro into broader ubnt support
  version/distro/distro.go
  wgengine/router/router_linux.go
  wgengine/router/router_linux_test.go
Labels: relnote

#14676 ipnlocal: allow overriding os.Hostname() via syspolicy
  ipn/ipnlocal/local.go
  util/syspolicy/policy_keys.go
Labels: mdm

#14727 cmd/tailscale: define CLI tools to manipulate macOS network and system extensions
  cmd/tailscale/cli/cli.go
  cmd/tailscale/cli/configure-kube.go
  cmd/tailscale/cli/configure-kube_omit.go
  cmd/tailscale/cli/configure-synology-cert.go
  cmd/tailscale/cli/configure-synology.go
  cmd/tailscale/cli/configure.go
  cmd/tailscale/cli/configure_apple-all.go
  cmd/tailscale/cli/configure_apple.go
Labels: cli
